services:
  ssh-notify:
    build: .
    container_name: ssh_notify
    tty: true
    restart: always
    user: root
    volumes:
      - /var/log/journal:/var/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    environment:
      - TZ=Europe/Prague
    env_file:
      - .env